export interface CompanionProfile {
  id: string;
  name: string;
  age: string;
  rating: string;
  category: "all" | "vip" | "russian" | "independent" | "college" | "resort";
  categoryName: string;
  location: string;
  price: string;
  image: string;
  alt: string;
  bio: string;
  tags: string[];
}

export const verifiedCompanions: CompanionProfile[] = [
  {
    id: "aisha-sharma",
    name: "Aisha Sharma",
    age: "22 Years",
    rating: "4.9",
    category: "vip",
    categoryName: "VIP Escort Model",
    location: "Lake Pichola Suites",
    price: "₹11,999",
    image: "/images/vip-escorts-udaipur-01.jpg",
    alt: "Aisha Sharma - Verified VIP Escort Service in Udaipur Lake Pichola COD",
    bio: "Sophisticated conversationalist with royal demeanor, ideal for palace cocktail dinners and private lakeside suites.",
    tags: ["High Society", "Palace Ready", "Bilingual"]
  },
  {
    id: "priya-rajput",
    name: "Priya Rajput",
    age: "24 Years",
    rating: "5.0",
    category: "vip",
    categoryName: "Celebrity Companion",
    location: "The Oberoi Udaivilas",
    price: "₹12,999",
    image: "/images/vip-escorts-udaipur-02.jpg",
    alt: "Priya Rajput - Celebrity Escorts in Udaipur Oberoi Udaivilas Cash on Delivery",
    bio: "Exquisite poise and elegance suited for high-profile business summits, resort getaways, and private celebrations.",
    tags: ["Corporate VIP", "Resort Dinners", "Discreet"]
  },
  {
    id: "natasha-petrova",
    name: "Natasha Petrova",
    age: "23 Years",
    rating: "5.0",
    category: "russian",
    categoryName: "Russian Escort Model",
    location: "The Leela Palace Udaipur",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-01.jpg",
    alt: "Natasha Petrova - Russian Escorts in Udaipur Leela Palace 100% COD",
    bio: "Statuesque international European model with glowing charm, offering unhurried luxury companionship across Udaipur.",
    tags: ["European Poise", "International VIP", "Regal Grace"]
  },
  {
    id: "elena-volkova",
    name: "Elena Volkova",
    age: "24 Years",
    rating: "4.9",
    category: "russian",
    categoryName: "Exotic Russian Companion",
    location: "Raffles Udaipur Resort",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-02.jpg",
    alt: "Elena Volkova - Russian Call Girls in Udaipur Luxury Resort COD",
    bio: "Graceful and charming foreign escort companion, perfect for island resort weekends, private pool suites, and candlelight dining.",
    tags: ["Statuesque", "Luxury Retreats", "Discreet Retainer"]
  },
  {
    id: "ananya-sen",
    name: "Ananya Sen",
    age: "23 Years",
    rating: "4.9",
    category: "independent",
    categoryName: "Independent Call Girl",
    location: "Fateh Sagar Lake",
    price: "₹6,999",
    image: "/images/independent-call-girls-udaipur-01.jpg",
    alt: "Ananya Sen - Independent Call Girls in Udaipur Fateh Sagar COD Verified",
    bio: "Warm, affectionate, and authentic independent companion free from rush, passionate about leisurely romantic lake dinners.",
    tags: ["Genuine Chemistry", "Unhurried Stays", "Warm Soul"]
  },
  {
    id: "riya-verma",
    name: "Riya Verma",
    age: "21 Years",
    rating: "4.8",
    category: "college",
    categoryName: "College Profile",
    location: "Hiran Magri VIP Corridor",
    price: "₹3,999",
    image: "/images/college-call-girls-udaipur-01.jpg",
    alt: "Riya Verma - College Girls Escort Service Udaipur Hiran Magri COD ₹3999",
    bio: "Cheerful, bubbly, and enthusiastic companion who brings vibrant local warmth and playful conversation to city holidays.",
    tags: ["Playful Aura", "Local Guide", "Budget Friendly"]
  },
  {
    id: "kavya-patel",
    name: "Kavya Patel",
    age: "22 Years",
    rating: "4.9",
    category: "independent",
    categoryName: "Independent Companion",
    location: "City Palace Heritage Area",
    price: "₹6,999",
    image: "/images/independent-call-girls-udaipur-02.jpg",
    alt: "Kavya Patel - Independent Escorts Udaipur City Palace Heritage Havelis",
    bio: "Gentle nature and attentive company, creating a calm, relaxing sanctuary for weary travelers visiting Udaipur.",
    tags: ["Tender Romance", "Discreet Haveli Dates", "Attentive"]
  },
  {
    id: "simran-kaur",
    name: "Simran Kaur",
    age: "25 Years",
    rating: "5.0",
    category: "vip",
    categoryName: "High Profile VIP Escort",
    location: "Taj Lake Palace Udaipur",
    price: "₹14,999",
    image: "/images/vip-escorts-udaipur-03.jpg",
    alt: "Simran Kaur - High Profile Udaipur Escorts Taj Lake Palace COD Guarantee",
    bio: "Fashion-forward, confident, and articulate companion with impeccable manners for palace gala events and private celebrations.",
    tags: ["High Fashion", "Palace Banquets", "Absolute Discretion"]
  },
  {
    id: "sofia-ivanova",
    name: "Sofia Ivanova",
    age: "22 Years",
    rating: "5.0",
    category: "russian",
    categoryName: "European Russian Escort",
    location: "Aurika Luxury Resort",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-03.jpg",
    alt: "Sofia Ivanova - Russian Escorts in Udaipur Aurika Resort 100% Cash on Delivery",
    bio: "Dazzling beauty with captivating aura, accustomed to 5-star hospitality, luxury spa days, and unhurried dinner romance.",
    tags: ["Blonde European", "Luxury Spa Dates", "Zero Advance"]
  },
  {
    id: "pooja-singhania",
    name: "Pooja Singhania",
    age: "24 Years",
    rating: "4.8",
    category: "resort",
    categoryName: "Resort & Villa Escort",
    location: "Haridas Ji Ki Magri",
    price: "₹8,999",
    image: "/images/luxury-resort-escorts-udaipur-01.jpg",
    alt: "Pooja Singhania - Luxury Resort Escorts in Udaipur Private Villa COD",
    bio: "Attuned to private pool villa stays and leisurely cocktail evenings under the starlit Mewar skies.",
    tags: ["Private Villa", "Poolside Stays", "Sensual Charm"]
  },
  {
    id: "tanvi-deshmukh",
    name: "Tanvi Deshmukh",
    age: "21 Years",
    rating: "4.8",
    category: "college",
    categoryName: "Modern College Escort",
    location: "Sukher & Celebration Hub",
    price: "₹3,999",
    image: "/images/college-call-girls-udaipur-02.jpg",
    alt: "Tanvi Deshmukh - College Call Girls in Udaipur Sukher COD Starting ₹3999",
    bio: "Sweet, conversational, and energetic companion who loves romantic rooftop cafes and pleasant evening walks.",
    tags: ["Youthful Charm", "Rooftop Cafes", "Fast 30-Min Dispatch"]
  },
  {
    id: "sana-mirza",
    name: "Sana Mirza",
    age: "26 Years",
    rating: "4.9",
    category: "vip",
    categoryName: "Elite High Society Escort",
    location: "Bhuwana & Shobhagpura",
    price: "₹11,999",
    image: "/images/vip-escorts-udaipur-04.jpg",
    alt: "Sana Mirza - VIP Call Girls in Udaipur Shobhagpura Cash on Delivery",
    bio: "Impeccably dressed with refined dining etiquette, perfect for luxury business dinners and private stays.",
    tags: ["Refined Manners", "Corporate Delegate", "Classy"]
  },
  {
    id: "daria-novikova",
    name: "Daria Novikova",
    age: "23 Years",
    rating: "4.9",
    category: "russian",
    categoryName: "Russian International Model",
    location: "Fateh Sagar Lakeside",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-04.jpg",
    alt: "Daria Novikova - Russian Escort Service in Udaipur Fateh Sagar Hotels COD",
    bio: "Enchanting eyes, statuesque figure, and cosmopolitan etiquette for luxury travelers seeking international elegance.",
    tags: ["Cosmopolitan", "Lake Promenades", "Verified Live Photo"]
  },
  {
    id: "aditi-sharma",
    name: "Aditi Sharma",
    age: "23 Years",
    rating: "4.9",
    category: "independent",
    categoryName: "Independent Escort",
    location: "Lake Pichola Heritage Havelis",
    price: "₹6,999",
    image: "/images/independent-call-girls-udaipur-03.jpg",
    alt: "Aditi Sharma - Independent Escorts in Udaipur Lake Pichola Verified by Neha Mam",
    bio: "Warm, respectful, and romantic, ensuring zero awkwardness and genuine emotional connection from the very first minute.",
    tags: ["Tender Care", "Heritage Haveli", "Zero Advance"]
  },
  {
    id: "meera-joshi",
    name: "Meera Joshi",
    age: "22 Years",
    rating: "4.7",
    category: "college",
    categoryName: "Campus Model Escort",
    location: "Goverdhan Vilas",
    price: "₹3,999",
    image: "/images/college-call-girls-udaipur-03.jpg",
    alt: "Meera Joshi - College Girl Escorts Udaipur Goverdhan Vilas COD ₹3999",
    bio: "Fresh face with natural beauty and charming hospitality, ideal companion for Udaipur weekend getaways.",
    tags: ["Casual Fun", "Weekend Dates", "Authentic Photo"]
  },
  {
    id: "krishna-rathore",
    name: "Krishna Rathore",
    age: "24 Years",
    rating: "5.0",
    category: "resort",
    categoryName: "Resort VIP Companion",
    location: "Debari & Airport Luxury Corridor",
    price: "₹9,999",
    image: "/images/luxury-resort-escorts-udaipur-02.jpg",
    alt: "Krishna Rathore - Luxury Resort Escort Service Udaipur Debari COD",
    bio: "Mewari royal grace combined with modern charm, suited for quiet palace suites and scenic romantic evenings.",
    tags: ["Mewari Hospitality", "Serene Dates", "Resort Dispatch"]
  },
  {
    id: "anastasia-kuznetsova",
    name: "Anastasia Kuznetsova",
    age: "25 Years",
    rating: "5.0",
    category: "russian",
    categoryName: "High Fashion Russian Escort",
    location: "The Leela Palace Villas",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-05.jpg",
    alt: "Anastasia Kuznetsova - Elite Russian Escorts Udaipur Leela Palace COD",
    bio: "Breathtaking European supermodel presence, offering exclusive VIP companion services for destination events.",
    tags: ["Supermodel", "Private Retainers", "100% COD"]
  },
  {
    id: "ishita-bhatia",
    name: "Ishita Bhatia",
    age: "23 Years",
    rating: "4.9",
    category: "vip",
    categoryName: "VIP Escort & Hostess",
    location: "Radisson Blu Udaipur",
    price: "₹11,999",
    image: "/images/vip-escorts-udaipur-05.jpg",
    alt: "Ishita Bhatia - VIP Escort Service in Udaipur Radisson Blu 100% Cash on Delivery",
    bio: "Intelligent conversationalist with a vivacious personality, beloved by corporate visitors and luxury guests.",
    tags: ["Corporate Hostess", "Cocktail Companion", "Discreet"]
  },
  {
    id: "shreya-malhotra",
    name: "Shreya Malhotra",
    age: "22 Years",
    rating: "4.8",
    category: "independent",
    categoryName: "Independent Call Girl",
    location: "Fateh Sagar Rani Road",
    price: "₹6,999",
    image: "/images/independent-call-girls-udaipur-04.jpg",
    alt: "Shreya Malhotra - Independent Call Girls in Udaipur Rani Road COD",
    bio: "Warm-hearted and naturally affectionate companion who loves sunset drives and peaceful candlelit dinners.",
    tags: ["Sunset Drives", "Affectionate", "Verified 18+"]
  },
  {
    id: "khushi-gupta",
    name: "Khushi Gupta",
    age: "21 Years",
    rating: "4.8",
    category: "college",
    categoryName: "Cheerful College Escort",
    location: "Celebration Mall Corridor",
    price: "₹3,999",
    image: "/images/college-call-girls-udaipur-04.jpg",
    alt: "Khushi Gupta - College Call Girls Udaipur Celebration Mall Area COD",
    bio: "Lively, sweet, and always smiling, bringing an infectious positive vibe to your holiday stay in Udaipur.",
    tags: ["Sweet Vibe", "Friendly", "Pocket Friendly"]
  },
  {
    id: "olga-smirnova",
    name: "Olga Smirnova",
    age: "24 Years",
    rating: "5.0",
    category: "russian",
    categoryName: "Exquisite Russian Model",
    location: "Taj Lake Palace Suites",
    price: "₹19,999",
    image: "/images/russian-call-girls-udaipur-06.jpg",
    alt: "Olga Smirnova - Russian Escorts in Udaipur Lake Palace Cash on Delivery",
    bio: "Stunning international beauty with warm etiquette, tailored for unforgettable lakeside palace evenings.",
    tags: ["European Model", "Palace Suites", "Private Retainer"]
  },
  {
    id: "divya-mehta",
    name: "Divya Mehta",
    age: "25 Years",
    rating: "4.9",
    category: "resort",
    categoryName: "Luxury Villa Escort",
    location: "Oberoi Udaivilas Villas",
    price: "₹9,999",
    image: "/images/luxury-resort-escorts-udaipur-03.jpg",
    alt: "Divya Mehta - Luxury Resort Call Girls Udaipur Oberoi Udaivilas COD",
    bio: "Attentive, discreet, and deeply soothing company for guests unwinding at luxury wellness retreats.",
    tags: ["Wellness Retreats", "Serene", "Private Dispatch"]
  },
  {
    id: "zoya-khan",
    name: "Zoya Khan",
    age: "23 Years",
    rating: "4.9",
    category: "vip",
    categoryName: "VIP Socialite Companion",
    location: "City Palace Heritage Suites",
    price: "₹12,999",
    image: "/images/vip-escorts-udaipur-06.jpg",
    alt: "Zoya Khan - VIP Escort Service in Udaipur City Palace Havelis 100% COD",
    bio: "Glamorous and cultured companion with flawless high-society charm, ready for memorable private dinners.",
    tags: ["High Society", "Glamour", "Complete Privacy"]
  },
  {
    id: "nidhi-chawla",
    name: "Nidhi Chawla",
    age: "22 Years",
    rating: "4.8",
    category: "independent",
    categoryName: "Independent Romance Escort",
    location: "Lake Pichola Promenade",
    price: "₹6,999",
    image: "/images/independent-call-girls-udaipur-05.jpg",
    alt: "Nidhi Chawla - Independent Escorts in Udaipur Lake Pichola Cash on Delivery",
    bio: "Caring, unhurried, and genuinely sweet companion who prioritizes genuine emotional warmth and private romantic moments.",
    tags: ["Romance Specialist", "Unhurried", "Zero Scam Policy"]
  }
];
